format:
  html: {toc: true, toc-depth: 4, theme: cosmo}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters: [index.qmd, pdshic.02_01_understanding_data_types_in_clojure.qmd]
  title: Python Data Science Handbook - in Clojure
